- name: Configure webserver with Software packages
  hosts: webserver
  become: True
  gather_facts: False
  vars:
    host_name: "{{ ansible_ssh_host }}"
  tasks:

    - name: "Installing RPMs"
      yum: name={{ item }} state=installed
      with_items:
       - git
       - telnet
       - httpd
       - libselinux-python
      notify: restart httpd


    - name: "Verify RPMs"
      yum: list={{ item }}
      with_items:
       - git
       - telnet
       - httpd

    - name: "Clone git repository"
      git: dest=/var/www/html repo=https://github.com/jeyaramji/web01.git update=no

    - name: "Copy index.html template"
      template: src=templates/index.html.j2 dest="/var/www/html/index.html"
#      with_items: host_name

  handlers:
      - name: restart httpd
        service: name=httpd state=restarted enabled=on


