- name: Configure webserver with Software packages
  hosts: webserver
  become: True
  gather_facts: False
  vars:
    host_name: "{{ ansible_ssh_host }}"
  tasks:
    - name: "Installing RPMs"
      yum: name={{ item }} state=installed
      with_items:
       - git
       - telnet
       - httpd
       - libselinux-python
      notify: restart httpd

    - name: "Verify RPMs"
      yum: list={{ item }}
      with_items:
       - git
       - telnet
       - httpd

    - name: "Clone git emz repository"
      git: dest=/var/www/html/emz repo=https://github.com/jeyaramji/emz.git update=no

#    - name: "Copy index.html template"
#      template: src=templates/index.html.j2 dest="/var/www/html/index.html"

  handlers:
      - name: restart httpd
        service: name=httpd state=restarted enabled=on
